name: Email DNS mini-audit
on:
  push:
  schedule:
    - cron: '0 3 * * 1'
jobs:
  dns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/check_mail_dns.sh spacerunner.com
